apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-spot-cluster
  region: ap-south1

manageNodeGroups:
  - name: ng-1
    instanceType: m5.large
    spot: true
    desiredCapacity: 3
    ssh:
      publicKeyPath: k8resc